version: '3'

services:
  influxdb:
    image: influxdb:2.6-alpine
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    restart: always
volumes:
  influxdbv2:
